### ISSUE TITLE
FFT correlation type

### ISSUE THREAD

**Issue by ErichZimmer** [Marc-3d/quickPIV#2]
Does quickPIV use circular or linear (padded) correlation? I see pad and padi, but don't know if that is zero-padding or not.

Regards,
Erich

**Comment by Marc-3d** [comment]
Hi Erich, 

It is zero padding. The cross-correlated image and the kernel are padded to the dimensions of the cross-correlation matrix to avoid circular convolution.

"padi" (or sometimes "padg") is the padded interrogation area, and "pads" or "padf" is the padded search area. 

At some point I started using the letters "f" and "g", because most formulas for cross correlation refer to functions "f" and "g".

**Comment by ErichZimmer** [comment]
When testing OpenPIV-c++, was it running circular correlation?

**Comment by ErichZimmer** [comment]
@Marc-3d ,
Is the interrogation windows padded by 2s or i x s-1, where i = interrogation windows and s = search area?

**Comment by Marc-3d** [comment]
I will give a 2D example to explain the paddings, considering "interArea = 5pixels" and "searchMargin = 2pixels". 

````julia

# 1-. we will have 5x5 interrogation areas
interSize  = ( interArea, interArea );           

# 2-. search area size of 9x9 pixels, or ( 2 + 5 + 2 ) x ( 2 + 5 + 2 ).  The search margin expands the 
# search areas in both sides for each dimensions. 
searchSize = interArea .+ 2 .* searchMargin; 

# NOTE: if the search area is too close to the border of image2, some rows/columns of the extended 
# search area will fall outside the limits of the image. These row/columns will be filled with 0's, and 
# this is achieved by considering an offset in step 7, when copying searchArea into "pads".

# 3-. The size of the cross-correlation should be N + M - 1.  In this example that should be 13x13.
ccrSize = interSize .+ searchSize .- 1; 

# 4-. But in practice I skip the " .- 1 " to keep the dimensions even, and hopefully get faster FFTs. 
# So for our purposes, ccrSize = 14x14. 
ccrSize = ccrSize .+ 1;                         
         
# 5-. Both the interrogation and search areas will be zero-padded to have the same size as ccrSize to
# avoid circular cross-correlation.           
padi = zeros( Complex{Float32}, ccrSize ); 
pads = zeros( Complex{Float32}, ccrsize ); 

# 6-. The interrogation area is simply copied into the top-left corner of "padi". Notice that within "padi",
# the zero-padding stays on the bottom and right sides of the interrogation area.
padi[ 1:interArea[1], 1:interArea[2] ] .= image1[ interrogation_area_coordinates... ]

# 7-. the search area is also copied into the top-left corner of "pads", like above. In this step, an extra offset
# can be added to the top-left coordinates of the search area inside "pads", to answer to the NOTE
# below step 2.
pads[ 1+off[1]:searchSize[1], 1+off[2]:searchSize[2] ] .= image2[ search_area_coordinates... ]

````

The only padding of the interrogation window is done in step 6, when copying it into padi. Since the size of padi is ````interSize .+ searchSize````, the extra padding corresponds to "searchSize", where ````searchSize = interSize .+ 2 .* searchMargin````.

**Comment by ErichZimmer** [comment]
Okay, that makes sense. It is very fast for linear correlation, much faster than my Cython attempt implemented in Python 3.8. Thank you for this neat PIV package :D

**Comment by ErichZimmer** [comment]
@Marc-3d 
When calling quickPIV through JuliaPy, I get some  "weird" results. Maybe there is a lossy conversion between Julia arrays and Numpy arrays?
Test was done on 193 synthetic images with velocity magnitudes ranging 0-6 pixels. 

![download](https://user-images.githubusercontent.com/69478071/151848419-fca091a5-fa44-4fd8-a32f-5f2fd4923389.png)


### settings:
OpenPIV-Python:
Padding: None
Normalization: None
Window size: 24x24
Overlap: 12x12
Subpixel estimator: 3 point gaussian

quickPIV:
Padding: 2n
Normalization: depends on correlation type
Window size: 24x24
Overlap: 12x12
Subpixel estimator: 3 point gaussian

**Comment by Marc-3d** [comment]
Are you applying the same translation in all directions?

If not, the problem might be that the Python and Julia vector fields store the first two vector components in opposite arrays. In quickPIV, U is the vertical component and V is the horizontal component. 

```` U, V = quickPIV.PIV( .... ); ````

Another issue might be that the vertical components (U) needs to be multiplied by -1, to go from image coordinates to cartesian coordinates. In image coordinates, negative offsets move up the rows, while positive offsets move down the rows of the image, which is the opposite of the Cartesian axes. 

I hope this helps.

**Comment by ErichZimmer** [comment]
On different vector field orientations, I am using velocity magnitudes to calculate bias and RMS errors, which in theory, negates aformentioned possible issues. I'll have to look into it a little more later when I have time.

**Comment by ErichZimmer** [comment]
FWI, I use `v, u = julia.eval("quickPIV.PIV( ... )")` to evaluate the image pairs.

**Comment by ErichZimmer** [comment]
I fixed this issue, but I don't how. The synthetic tests are looking good now and compares well to OpenPIV-Python's single pass evaluations.

**Comment by Marc-3d** [comment]
Sorry for the late answer, I must have missed the notifications. I am happy to hear that things are working now. 

I don't quite understand the "julia.eval" code. Is it a way to call julia from Python?

**Comment by ErichZimmer** [comment]
Yes. Julia.eval( ... ) is the python call to a Julia kernel.

On the "high" RMS and bias errors for the linear correlation algorithms, it was solved by subtracting the mean of every interrogation window.

**Comment by ErichZimmer** [comment]
There were high spectral frequencies caused by the zero-padded FFT cross correlation that were removed by subtracting the mean.

**Comment by ErichZimmer** [comment]
Yikes!, I think it was user error as `putWithinPadded` subtracts the mean, so I am back to not knowing what I did to make it better other than playing around with circular and linear correlation.
