### ISSUE TITLE
Rectangular windows

### ISSUE THREAD

**Issue by ErichZimmer** [Marc-3d/quickPIV#3]
Is there a chance quickPIV can incorporate rectangular windows?  Shouldn't be too hard (in theory).

**Comment by Marc-3d** [comment]
you can already set the interSize to a tuple, allowing to provide a different size for each dimension. Same goes for searchMargin and overlap. 

For example: 

````julia

 params = quickPIV.setPIVParameters.( interSize = (16,32,4), searchMargin = (0,0,8), overlap= (8,8,0) ); 

````
