### ISSUE TITLE
MethodError: no method matching PIV

### ISSUE THREAD

**Issue by ErichZimmer** [Marc-3d/quickPIV#4]
I already have miniconda installed with Jupyter and just installed Julia 1.7.1. I tried calling quickPIV through JupyterLab, but an error told me to install `ImageMagick`. Once that was done, I successfully loaded a PIV image pair, but the function `PIV` is not found on the module `quickPIV`.

OS: Windows 10 Pro
CPU Intel pentium
GPU: integrated
Julia version: v1.7.1
JupyterLab version: v2.2.5

Followed your instructions on readme.md for loading .BMP images that are 1600x1300 px for the y-axis and x-axis respectively, the error only occured when trying to call `quickPIV.PIV`.

**Comment by Marc-3d** [comment]
If you are loading the image with FileIO, the problem might be that FileIO.load( "\path\to\image" ) loads RGB images
as 2D arrays whose elements are ColorTypes.RGB{FixedPointNumbers.N0f8}.  

````quickPIV.PIV```` expects the inputs to be arrays of primitive types, like Float32 or Int64. 

To get a grayscale image of Floats32 (for example) from the ColorTypes.RGB you can run this line:
```` 
using FileIO, ColorTypes

grayFloat = Float32.( ColorTypes.Gray.( FileIO.load( "\path\to\image" ) ) ); 
``````

**Comment by ErichZimmer** [comment]
That works, thank you.
